apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-sample-app
  namespace: observability
  labels:
    app.kubernetes.io/name: otel-sample-app
    app.kubernetes.io/part-of: observability
automountServiceAccountToken: true
