apiVersion: v1
kind: Service
metadata:
  name: otel-sample-app
  namespace: observability
  labels:
    app.kubernetes.io/name: otel-sample-app
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: observability
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: otel-sample-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
